version: '3.9'

services:
  db:
    image: postgres:17.0-alpine
    restart: always
    environment:
      POSTGRES_DB: images
      POSTGRES_USER: images
      POSTGRES_PASSWORD: images
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://images:images@db:5432/images
    depends_on:
      - db

volumes:
  postgres_data:
  media_data:
  static_data:
