# Generated by Django 5.2.7 on 2025-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title for the image.", max_length=255),
                ),
                ("image_file", models.ImageField(upload_to="uploads/")),
                (
                    "width",
                    models.PositiveIntegerField(
                        editable=False, help_text="Width of the image after resizing."
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        editable=False, help_text="Height of the image after resizing."
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
